# Generated by Django 5.2.10 on 2026-02-24 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_meterreading_reading_status'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
        ('payments', '0001_initial'),
        ('tenant_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalpayment',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='component',
            field=models.CharField(choices=[('WATER', 'Water Charge'), ('PENALTY', 'Penalty'), ('INTEREST', 'Interest'), ('METER_RENT', 'Meter Rental'), ('SERVICE_FEE', 'Service Fee'), ('OPERATION_FEE', 'Operation Fee'), ('OTHER', 'Other Charges')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED')), fields=('bill',), name='one_completed_payment_per_bill'),
        ),
    ]
