# Generated by Django 5.2.10 on 2026-02-25 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashiersession_tenant_externalpayment_tenant_and_more'),
        ('tenant_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
        migrations.AddConstraint(
            model_name='cashiersession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('tenant', 'cashier'), name='one_open_session_per_cashier'),
        ),
    ]
