# Generated by Django 5.2.10 on 2026-02-25 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cashiersession_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='cash_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='physical_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashiersession',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
    ]
