# Generated by Django 5.2.10 on 2026-02-25 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_cashiersession_cash_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiersession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='payments.payment'),
        ),
    ]
