# Generated by Django 5.2.10 on 2026-02-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_cashiersession_payment'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='signature_hash',
            field=models.CharField(default='no', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='unique_receipt_per_tenant'),
        ),
    ]
