# Generated by Django 5.2.10 on 2026-02-25 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_meterreading_unique_together_and_more'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
        ('payments', '0006_receipt_signature_hash_alter_receipt_payment_and_more'),
        ('tenant_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashiersession',
            name='one_open_session_per_cashier',
        ),
        migrations.RemoveField(
            model_name='cashiersession',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='cashiersession',
            name='payment',
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='session_type',
            field=models.CharField(choices=[('CASHIER', 'Cashier'), ('SYSTEM', 'System')], default='CASHIER', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashiersession',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_by'], name='payments_pa_receive_784dc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashiersession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), ('session_type', 'CASHIER')), fields=('tenant', 'cashier'), name='one_open_cashier_session_per_user'),
        ),
    ]
