# Generated by Django 5.2.10 on 2026-02-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_cashiersession_one_open_session_per_cashier_and_more'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
    ]
