# Generated by Django 5.2.10 on 2026-02-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_branch'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
    ]
