# Generated by Django 5.2.10 on 2026-03-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_cashiersession_branch_paymentallocation_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
