# Generated by Django 5.2.10 on 2026-03-03 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_meterreading_unique_together_and_more'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
        ('payments', '0011_payment_is_reversal_payment_reversal_of_and_more'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0003_remove_auditlog_tenant_util_tenant__7e1b3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='one_completed_payment_per_bill',
        ),
        migrations.AlterField(
            model_name='paymentreversalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversal', False), ('status', 'COMPLETED')), fields=('bill',), name='one_completed_payment_per_bill'),
        ),
    ]
