# Generated by Django 5.2.10 on 2026-03-04 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_meterreading_unique_together_and_more'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
        ('payments', '0012_remove_payment_one_completed_payment_per_bill_and_more'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0003_remove_auditlog_tenant_util_tenant__7e1b3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill', 'status'], name='payments_pa_bill_id_ffa04d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreversal',
            index=models.Index(fields=['reversed_at'], name='payments_pa_reverse_9067d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_reversal', False), ('reversal_of', None)), models.Q(('is_reversal', True), ('reversal_of__isnull', False)), _connector='OR'), name='valid_reversal_relationship'),
        ),
    ]
