# Generated by Django 5.2.10 on 2026-03-24 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_bill_bills_bill_issue_d_3442dd_idx_and_more'),
        ('customers', '0010_customer_customers_c_tenant__7bbedf_idx'),
        ('payments', '0013_payment_payments_pa_bill_id_ffa04d_idx_and_more'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0004_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_reversal'], name='payments_pa_is_reve_81ef48_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['component'], name='payments_pa_compone_a8a538_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='payments_pa_payment_bc6702_idx'),
        ),
    ]
