# Generated by Django 5.2.10 on 2026-04-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_payments_pa_is_reve_81ef48_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiersession',
            options={'permissions': [('open_cashier_session', 'Can open cashier session'), ('close_cashier_session', 'Can close cashier session'), ('approve_cashier_session', 'Can approve cashier session'), ('view_cashier_reports', 'Can view cashier reports')]},
        ),
    ]
