# Generated by Django 5.2.10 on 2026-02-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_branch_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tenant_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
