# Generated by Django 5.2.10 on 2026-02-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_branch_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_branch_member',
            new_name='is_branch_admin',
        ),
    ]
