# Generated by Django 5.2.10 on 2026-02-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_branch_member_customuser_is_branch_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_tenant_admin',
            new_name='is_admin',
        ),
    ]
