# Generated by Django 5.2.10 on 2026-02-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_is_admin_and_more'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('INVITE_SENT', 'Invite sent'), ('INVITE_ACCEPTED', 'Invite accepted'), ('INVITE_REVOKED', 'Invite revoked'), ('INVITE_EXPIRED', 'Invite expired'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_REACTIVATED', 'User reactivated'), ('ROLE_ASSIGNED', 'Role assigned'), ('ROLE_REMOVED', 'Role removed'), ('ROLE_PERMS_CHANGED', 'Role permissions changed'), ('PAYMENT_CREATED', 'Payment created'), ('PAYMENT_COMPLETED', 'Payment completed'), ('PAYMENT_REVERSED', 'Payment reversed'), ('SESSION_OPENED', 'Session opened'), ('SESSION_CLOSE_REQUESTED', 'Session close requested'), ('SESSION_CLOSED', 'Session closed'), ('SESSION_APPROVED', 'Session approved'), ('EXTERNAL_PAYMENT_RECEIVED', 'External payment received'), ('EXTERNAL_PAYMENT_POSTED', 'External payment posted'), ('RECEIPT_GENERATED', 'Receipt generated'), ('GENERIC', 'Generic')], db_index=True, default='GENERIC', max_length=64),
        ),
    ]
