# Generated by Django 5.2.10 on 2026-03-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_auditlog_branch_alter_auditlog_action'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tenantuserrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tenantuserrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'tenant'), name='unique_user_role_per_tenant', violation_error_message='This user already has this role in this tenant.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='role_templates', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roletemplate'),
        ),
    ]
