# Generated by Django 5.2.10 on 2026-03-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_roletemplate_alter_tenantuserrole_unique_together_and_more'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenant_manager.tenant'),
        ),
    ]
