# Generated by Django 5.2.10 on 2026-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantrolepermission',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tenantrolepermission',
            unique_together=set(),
        ),
    ]
