# Generated by Django 5.2.10 on 2026-02-13 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenant_manager.tenant')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ('tenant_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_branch_admin', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant_utils.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to='tenant_manager.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_user_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Membership',
                'verbose_name_plural': 'Branch Memberships',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'code'], name='tenant_util_tenant__323f13_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_util_tenant__de63c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='branchmembership',
            index=models.Index(fields=['tenant', 'user'], name='tenant_util_tenant__4df774_idx'),
        ),
        migrations.AddIndex(
            model_name='branchmembership',
            index=models.Index(fields=['tenant', 'branch'], name='tenant_util_tenant__57ea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='branchmembership',
            index=models.Index(fields=['tenant', 'user', 'is_active'], name='tenant_util_tenant__f37a3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchmembership',
            unique_together={('tenant', 'user', 'branch')},
        ),
    ]
