# Generated by Django 5.2.10 on 2026-02-27 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INVITE_SENT', 'Invite sent'), ('INVITE_ACCEPTED', 'Invite accepted'), ('INVITE_REVOKED', 'Invite revoked'), ('INVITE_EXPIRED', 'Invite expired'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_REACTIVATED', 'User reactivated'), ('ROLE_ASSIGNED', 'Role assigned'), ('ROLE_REMOVED', 'Role removed'), ('ROLE_PERMS_CHANGED', 'Role permissions changed'), ('PAYMENT_CREATED', 'Payment created'), ('PAYMENT_COMPLETED', 'Payment completed'), ('PAYMENT_REVERSED', 'Payment reversed'), ('SESSION_OPENED', 'Session opened'), ('SESSION_CLOSE_REQUESTED', 'Session close requested'), ('SESSION_CLOSED', 'Session closed'), ('SESSION_APPROVED', 'Session approved'), ('EXTERNAL_PAYMENT_RECEIVED', 'External payment received'), ('EXTERNAL_PAYMENT_POSTED', 'External payment posted'), ('RECEIPT_GENERATED', 'Receipt generated'), ('GENERIC', 'Generic')], db_index=True, default='GENERIC', max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=128)),
                ('target_pk', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_audit_logs', to='tenant_utils.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_audit_logs', to='tenant_manager.tenant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='tenant_util_tenant__7e1b3a_idx'), models.Index(fields=['tenant', 'action', 'created_at'], name='tenant_util_tenant__81f780_idx'), models.Index(fields=['tenant', 'target_model', 'target_pk'], name='tenant_util_tenant__567f1f_idx')],
            },
        ),
    ]
