# Generated by Django 5.2.10 on 2026-02-27 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_utils', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tenant_util_tenant__7e1b3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tenant_util_tenant__81f780_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tenant_util_tenant__567f1f_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['branch', 'created_at'], name='tenant_util_branch__7846de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['branch', 'action', 'created_at'], name='tenant_util_branch__553479_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['branch', 'target_model', 'target_pk'], name='tenant_util_branch__b04ede_idx'),
        ),
    ]
