# Generated by Django 5.2.10 on 2026-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_utils', '0004_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='key',
            new_name='hashed_key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
