# Generated by Django 5.2.10 on 2026-02-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_period', models.DateField()),
                ('status', models.CharField(choices=[('UNSOLD', 'Unsold'), ('SOLD', 'Sold'), ('VOIDED', 'Voided')], default='UNSOLD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meter_rental_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30)),
                ('bill_overdue_in_days', models.PositiveIntegerField(default=15)),
                ('service_charge_fee', models.PositiveIntegerField(default=10)),
                ('manual_bill_generation', models.BooleanField(default=True)),
                ('bill_generation_date', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='BlockRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(auto_now_add=True)),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_status', models.CharField(choices=[('INITIAL', 'Initial'), ('FRESH', 'Fresh'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('EDITED', 'Edited')], default='FRESH', max_length=10)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='SoldBillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('audited', models.BooleanField(default=False)),
                ('auditor', models.CharField(blank=True, max_length=100, null=True)),
                ('audited_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
