# Generated by Django 5.2.10 on 2026-02-13 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='customers.meter'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='customers.meter'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soldbillreport',
            name='bills',
            field=models.ManyToManyField(related_name='reports', to='bills.bill'),
        ),
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together={('meter', 'reading_date')},
        ),
    ]
