# Generated by Django 5.2.10 on 2026-02-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockrate',
            options={'ordering': ['start_unit']},
        ),
        migrations.AddField(
            model_name='bill',
            name='tenant',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='tenant',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockrate',
            name='tenant',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meterreading',
            name='tenant',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldbillreport',
            name='tenant',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='billingsettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_billing_settings_per_tenant'),
        ),
    ]
