# Generated by Django 5.2.10 on 2026-02-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_blockrate_options_bill_tenant_and_more'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_utils.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='operation_charge_fee',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_utils.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldbillreport',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_utils.branch'),
            preserve_default=False,
        ),
    ]
