# Generated by Django 5.2.10 on 2026-02-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_branch_billingsettings_operation_charge_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockrate',
            old_name='rate',
            new_name='COM',
        ),
        migrations.AddField(
            model_name='blockrate',
            name='GOV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockrate',
            name='IND',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockrate',
            name='PUB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockrate',
            name='RES',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
