# Generated by Django 5.2.10 on 2026-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rename_rate_blockrate_com_blockrate_gov_and_more'),
        ('customers', '0008_meter_branch'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='operation_charge_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='service_charge_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('tenant', 'meter', 'bill_period'), name='unique_bill_per_period_per_meter'),
        ),
    ]
