# Generated by Django 5.2.10 on 2026-02-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='bills.meterreading'),
        ),
    ]
