# Generated by Django 5.2.10 on 2026-02-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_reading'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='bills.meterreading'),
        ),
    ]
