# Generated by Django 5.2.10 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_bill_void_reason_bill_voided_at_bill_voided_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading_status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('FRESH', 'Fresh'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('BILVOIDED', 'Bill Voided'), ('EDITED', 'Edited')], default='FRESH', max_length=10),
        ),
    ]
