# Generated by Django 5.2.10 on 2026-02-25 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_meterreading_reading_status'),
        ('customers', '0009_customer_unique_customer_per_tenant_and_more'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('meter', 'reading_date'), name='unique_meter_reading_date', violation_error_message='A reading for this meter on this date already exists.'),
        ),
    ]
