# Generated by Django 5.2.10 on 2026-03-11 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_meterreading_unique_together_and_more'),
        ('customers', '0010_customer_customers_c_tenant__7bbedf_idx'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0003_remove_auditlog_tenant_util_tenant__7e1b3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['issue_date'], name='bills_bill_issue_d_3442dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['tenant', 'issue_date'], name='bills_bill_tenant__1cb72e_idx'),
        ),
        migrations.AlterConstraint(
            model_name='bill',
            name='unique_bill_per_period_per_meter',
            constraint=models.UniqueConstraint(fields=('tenant', 'meter', 'bill_period'), name='unique_bill_per_period_per_meter', violation_error_message='Bill for this period is already generated'),
        ),
    ]
