# Generated by Django 5.2.10 on 2026-02-13 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bills', models.ManyToManyField(related_name='bill_reports', to='bills.bill')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashierSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_bank', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_mobile', models.DecimalField(decimal_places=2, max_digits=15)),
                ('system_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('physical_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_cashier_reports', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='payments.cashiersession')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_reports', to=settings.AUTH_USER_MODEL)),
                ('payments', models.ManyToManyField(related_name='collection_reports', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingBalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outstanding_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
