# Generated by Django 5.2.10 on 2026-02-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrailreport',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billreport',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashiersessionreport',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outstandingbalancereport',
            name='tenant',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
            preserve_default=False,
        ),
    ]
