# Generated by Django 5.2.10 on 2026-03-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_audittrailreport_tenant_billreport_tenant_and_more'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('total_meters', models.PositiveIntegerField(default=0)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'month'), name='unique_monthly_statistics')],
            },
        ),
        migrations.CreateModel(
            name='YearlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_customers', models.PositiveIntegerField()),
                ('total_meters', models.PositiveIntegerField()),
                ('total_assignments', models.PositiveIntegerField()),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'year'), name='unique_yearly_statistics')],
            },
        ),
    ]
