# Generated by Django 5.2.10 on 2026-03-10 01:54

from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_meterreading_unique_together_and_more'),
        ('reports', '0003_monthlystatistics_yearlystatistics'),
        ('tenant_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='billreport',
            name='start_date',
        ),
        migrations.AddField(
            model_name='billreport',
            name='billing_month',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='billreport',
            constraint=models.UniqueConstraint(fields=('tenant', 'billing_month'), name='unique_billing_month_report'),
        ),
    ]
