# Generated by Django 5.2.10 on 2026-03-10 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_payments_pa_bill_id_ffa04d_idx_and_more'),
        ('reports', '0004_remove_billreport_end_date_and_more'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0003_remove_auditlog_tenant_util_tenant__7e1b3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='collectionreport',
            name='start_date',
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_utils.branch'),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='collection_month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='payment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='reversed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='collectionreport',
            name='total_mobile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name='collectionreport',
            constraint=models.UniqueConstraint(fields=('tenant', 'collection_month', 'branch'), name='unique_collection_report_per_branch'),
        ),
    ]
