# Generated by Django 5.2.10 on 2026-02-17 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_kebele_customer_kebele_woreda_customer_woreda'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebele',
            name='woreda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kebeles', to='customers.woreda'),
        ),
    ]
