# Generated by Django 5.2.10 on 2026-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('GAS', 'Gas')], default='WATER', max_length=50),
        ),
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAULTY', 'Faulty'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=10),
        ),
    ]
