# Generated by Django 5.2.10 on 2026-02-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_meter_meter_type_alter_meter_status'),
        ('tenant_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_utils.branch'),
            preserve_default=False,
        ),
    ]
