# Generated by Django 5.2.10 on 2026-02-20 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_meter_branch'),
        ('tenant_manager', '0001_initial'),
        ('tenant_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer_no'), name='unique_customer_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('tenant', 'meter_number'), name='unique_meter_per_tenant'),
        ),
    ]
