# Generated by Django 5.2.10 on 2026-03-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_customers_c_tenant__7bbedf_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(editable=False, unique=True),
        ),
    ]
